### ISSUE TITLE
Change meeting times for Project Management

### ISSUE THREAD

**Issue by mxajPrice** [hackforla/communities-of-practice#10]
### Overview
The meeting times for the PM CoP need to be updated on the communities-of-practice repo.

### Action Items
- Update the meeting times for the PM CoP on the [CoP repo](https://github.com/hackforla/communities-of-practice#our-communities) to Fridays at 12:00pm PT.

**Comment by ExperimentsInHonesty** [comment]
done 
![image](https://github.com/hackforla/communities-of-practice/assets/37763229/3840ea45-ccab-4a46-98fb-f669840b30ce)
